define GETTERS
	width:int
	height:int
	buff:char*
	view:void*
endef

define SETTERS
	bind_view:void*
	bind_buff:void*
endef

define METHODS
	create_null
	create
	populate
	load
	read_at
	vread_at
	write_at
	print
endef

include ../Makefile
