define GETTERS
	x:int
	y:int
	map:void*
endef

define SETTERS
	set_x:int
	set_y:int
	bind_map:void*
endef

define METHODS
	create_null
	write
	read
	from_index
	print
	read
	write
	move
	safe_move
	swap
	on_command
endef
	
include ../Makefile
