define GETTERS
	x:int
	y:int
endef

define SETTERS
	set_x:int
	set_y:int
endef

define CONSTRUCTORS
	create_null
	create
	from_index
endef

define DECONSTRUCTORS
	destroy
endef

define PRINTERS
	print
endef

define MOVEMENTS
	move_up
	move_down
	move_left
	move_right
endef

define METHODS
	$(CONSTRUCTORS)
	$(DECONSTRUCTORS)
	$(MOVEMENTS)
	$(PRINTERS)
	read
	write
endef
	
include ../Makefile
