define GETTERS
	data:void**
	length:int
	maxsize:int
	stepsize:int
endef

define SETTERS
	bind_data:void**
	set_length:int
	set_maxsize:int
	set_stepsize:int
endef

define METHODS
	create_null
	create
	create_default
	copy
	destroy
	increase_max_size
	skim
	print
	printf
	read_at
	pop
	write_at
	push
	foreach
	reduce
	morph
	copy_data
	strchr
endef

include ../Makefile
