define GETTERS
	data:void**
	length:int
	maxsize:int
	stepsize:int
endef

define SETTERS
	bind_data:void**
	set_length:int
	set_maxsize:int
	set_stepsize:int
endef
define METHODS
	increase_max_size
	create
	destroy
	print
	push
	pop
	read_at
	write_at
	foreach
endef

include ../Makefile
